name: Run isort
on:
  - push

jobs:
  pass:
    name: "Run isort (Expected to pass)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: jamescurtin/isort-action@v0
        with:
          requirementsFiles: "requirements.txt"
          sortPaths: "example/pass.py"
  fail:
    name: "Run isort (Expected to fail)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: jamescurtin/isort-action@v0
        with:
          requirementsFiles: "requirements.txt"
